---
driver_plugin: ec2
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>

provisioner:
  name: chef_zero

platforms:
- name: ec2
  driver_plugin: ec2
  driver_config:
    username: ubuntu
    image_id: <%= ENV['DEFAULT_VPC_IMAGE'] %>
    ssh_key: <%= ENV['AWS_PRIVATE_KEY_PATH'] %>
    flavor_id: t2.medium
    subnet_id: <%= ENV['AWS_SUBNET_ID'] %>
    security_group_ids: []

suites:
- name: default
  run_list:
  - recipe[scalex_test]
  attributes:
